name: CI-Firebase-hosting

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '12.x'
      #- run: npm install
      #- run: npm run build
          #npm i
      - run: |
          ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}